# 1. Read file from GITHUB

In [382]:
import pandas as pd
import numpy as np

In [383]:
# Raw GitHub URL for the CSV file
url = 'https://raw.githubusercontent.com/hitrangnek/eiu_aspire_project/refs/heads/main/initial_vendor_list.csv?token=GHSAT0AAAAAADCDCYXT7PL2AZGELE7ENLLKZ72JBTQ'
# Read the CSV file
df = pd.read_csv(url)

# Show the first few rows
df.head(3)

,Id_company,Company Name,Id_company.1,Address,Website,Email,Phone,MST,Establish year,Size,Key customers,Key Product,Notes
0,a75ky23s,Công ty Cổ phần Đầu tư Thương mại và Phát triể...,a75ky23s,"Lô B7 & B8, ngõ 187 Nguyễn Tuân, Nhân Chính, T...",https://uavvietnam.net/,admin@hoabinh.org,0243.5656.898,0106735244,NaN,NaN,NaN,NaN,NaN
1,m68oe69b,Công Ty Cổ Phần Sundrone Việt Nam,m68oe69b,"U2-15 đường số 5, khu dân cư Miền Nam, Phường ...",https://sundrone.vn/,contact@sundrone.vn,052 233 7799,1801734798,NaN,NaN,NaN,NaN,NaN
2,e18ju91m,CÔNG TY TNHH THIẾT BỊ BAY PHƯƠNG TÍN,e18ju91m,"Số 40 Lý Thái Tổ, Đông Kinh, Lạng Sơn",https://phuongtindrone.vn/,NaN,056 800 0888,4900890666,NaN,NaN,NaN,NaN,NaN

# 2. Preprocessing Data

In [384]:
df1=df.copy()

In [385]:
import pandas as pd

# Assuming 'df' is your DataFrame
# First, let's check the columns available in the DataFrame
print(df1.columns)

# Optionally strip spaces in column names if there are any issues with extra spaces
df1.columns = df1.columns.str.strip()

# Select the desired columns, if they exist in the DataFrame
if 'Id_company' in df1.columns and 'Phone' in df1.columns:
    data = df1[['Id_company', 'Phone']]
    print(data.head())
else:
    print("The columns 'Id_company' or 'Phone' do not exist in the DataFrame.")

Index(['Id_company', 'Company Name', 'Id_company.1', 'Address', 'Website ',
       'Email ', 'Phone ', 'MST ', 'Establish year', 'Size ', 'Key customers ',
       'Key Product ', 'Notes '],
      dtype='object')
  Id_company          Phone
0   a75ky23s  0243.5656.898
1   m68oe69b   052 233 7799
2   e18ju91m   056 800 0888
3   q92yc39y  1800 28 28 59
4   z23gg78s   0985.649.219

In [386]:
data.head(276)

    Id_company          Phone
0     a75ky23s  0243.5656.898
1     m68oe69b   052 233 7799
2     e18ju91m   056 800 0888
3     q92yc39y  1800 28 28 59
4     z23gg78s   0985.649.219
..         ...            ...
271   a72kv92y   0982 272 271
272   t55uj39k   0907 520 720
273   k94lu25c   0903 556 669
274   x55rh50v   0914 874 358
275   j61yg65p     0975728241

[276 rows x 2 columns]

In [387]:
data.dtypes

Id_company    object
Phone         object
dtype: object

1. Modify the phone number to replace the country code +84 with 0.
2. Convert dots (.) in the phone numbers
3. Remove any remaining spaces to normalize the phone numbers

In [388]:
data['Phone'] = data['Phone'].str.replace(r'\+84', '0', regex=True)
data['Phone'] = data['Phone'].str.replace(r'\.', '', regex=True)
data['Phone'] = data['Phone'].str.replace(r'[() ]', '', regex=True)
data['Phone'] = data['Phone'].str.replace(r'^(\+84|0084|84)', '0', regex=True)

<ipython-input-388-febcd7d926cc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone'] = data['Phone'].str.replace(r'\+84', '0', regex=True)
<ipython-input-388-febcd7d926cc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone'] = data['Phone'].str.replace(r'\.', '', regex=True)
<ipython-input-388-febcd7d926cc>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone'] = data['Phone'].str.replace(r'[() ]', '', regex=True)
<ipython-input-388-febcd7d926cc>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone'] = data['Phone'].str.replace(r'^(\+84|0084|84)', '0', regex=True)

4. Caculate in columns ( <13 characters) and remove "-" with "" for the first .

Normally, Vietnamese phone number have the length from 10-11. And some of rows in the dataset have 2 phone numbers, based on that => select thresolf of 13 to remove '-' , some of case 2 phone number connect with '-', difficult to preprocessing if choose this case.*

In [389]:
def process_phone_numbers(data):
    # def function to preprocessing number_phone
    def process_number(phone):
        # Loại bỏ dấu "-" và đếm số ký tự #Remove "-"
        phone = phone.replace('-', '')

        # Check the length of character <=13
        if len(phone) <= 13:
            return phone
        return phone  # If longer is longer 13, keep

    # Apply the function
    data['Processed_Phone'] = data['Phone'].apply(process_number)

    return data

In [390]:
data['Phone'] = data['Phone'].str.replace(r'\.', '', regex=True)  # Remove "."
data['Phone'] = data['Phone'].str.replace(r'\s', '', regex=True)  # Remove empty space

<ipython-input-390-51cde6fb7840>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone'] = data['Phone'].str.replace(r'\.', '', regex=True)  # Remove "."
<ipython-input-390-51cde6fb7840>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone'] = data['Phone'].str.replace(r'\s', '', regex=True)  # Remove empty space

In [391]:
def remove_non_numeric_characters(data):
    # Check the column names in the DataFrame to ensure the column names are correct
    print(data.columns)  # Display the column names in the DataFrame

    # Function to process phone numbers
    def process_number(phone):
        # Replace all non-numeric characters (letters, commas, spaces, etc.) with a '*'."
        phone = ''.join([i if i.isdigit() else '*' for i in phone])  # Chỉ thay ký tự không phải số bằng "*"
        return phone

    # Apply the processing function to the 'Phone' column
    data['Phone'] = data['Phone'].apply(process_number)

    # Rename the 'Phone' column to 'phone_number_1
    data.rename(columns={'Phone': 'phone_number_1'}, inplace=True)

    return data

processed_data = remove_non_numeric_characters(data)

# Display the results
print(processed_data[['phone_number_1']].head())

Index(['Id_company', 'Phone'], dtype='object')
  phone_number_1
0    02435656898
1     0522337799
2     0568000888
3     1800282859
4     0985649219

<ipython-input-391-04ca51d8612f>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Phone'] = data['Phone'].apply(process_number)
<ipython-input-391-04ca51d8612f>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns={'Phone': 'phone_number_1'}, inplace=True)

In [392]:
def process_phone_numbers_and_count(data):
    # Count the number of characters in the 'phone_number_1' column.
    char_count = data['phone_number_1'].apply(lambda x: pd.Series(list(x))).stack().value_counts()

    # Def function for preprocessing phone_number
    def process_number(phone):
        if len(phone) > 15:
            # "Cut the part after the '*' and store it in phone_number_2.
            phone_number_1 = phone.split('*')[0]
            phone_number_2 = phone.split('*')[1] if len(phone.split('*')) > 1 else None
            return phone_number_1, phone_number_2
        else:
            # If the length is less than or equal to 15, keep it unchanged
            return phone, None

    # Apply the processing function to the 'phone_number_1' column
    data[['phone_number_1', 'phone_number_2']] = data['phone_number_1'].apply(lambda x: pd.Series(process_number(x)))

    return data, char_count

processed_data = data
processed_data, char_count = process_phone_numbers_and_count(processed_data)

<ipython-input-392-9d4b9399e311>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['phone_number_1', 'phone_number_2']] = data['phone_number_1'].apply(lambda x: pd.Series(process_number(x)))
<ipython-input-392-9d4b9399e311>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['phone_number_1', 'phone_number_2']] = data['phone_number_1'].apply(lambda x: pd.Series(process_number(x)))

In [393]:
processed_data.head

<bound method NDFrame.head of     Id_company phone_number_1 phone_number_2
0     a75ky23s    02435656898           None
1     m68oe69b     0522337799           None
2     e18ju91m     0568000888           None
3     q92yc39y     1800282859           None
4     z23gg78s     0985649219           None
..         ...            ...            ...
271   a72kv92y     0982272271           None
272   t55uj39k     0907520720           None
273   k94lu25c     0903556669           None
274   x55rh50v     0914874358           None
275   j61yg65p     0975728241           None

[276 rows x 3 columns]>

# Preprocess the phone_number_1

In [394]:
processed_data['phone_number_1'] = processed_data['phone_number_1'].str.replace('*', '', regex=False)
processed_data['count_number_phone_1'] = processed_data['phone_number_1'].str.len()
print(processed_data[['phone_number_1', 'count_number_phone_1']].head())

  phone_number_1  count_number_phone_1
0    02435656898                    11
1     0522337799                    10
2     0568000888                    10
3     1800282859                    10
4     0985649219                    10

<ipython-input-394-e1e6b9ec94e8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data['phone_number_1'] = processed_data['phone_number_1'].str.replace('*', '', regex=False)
<ipython-input-394-e1e6b9ec94e8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data['count_number_phone_1'] = processed_data['phone_number_1'].str.len()

In [395]:
processed_data

    Id_company phone_number_1 phone_number_2  count_number_phone_1
0     a75ky23s    02435656898           None                    11
1     m68oe69b     0522337799           None                    10
2     e18ju91m     0568000888           None                    10
3     q92yc39y     1800282859           None                    10
4     z23gg78s     0985649219           None                    10
..         ...            ...            ...                   ...
271   a72kv92y     0982272271           None                    10
272   t55uj39k     0907520720           None                    10
273   k94lu25c     0903556669           None                    10
274   x55rh50v     0914874358           None                    10
275   j61yg65p     0975728241           None                    10

[276 rows x 4 columns]

In [396]:
processed_data['count_number_phone_1'].value_counts()

count_number_phone_1
10    189
11     77
9       6
12      2
8       2
Name: count, dtype: int64

**A. 8 characters in phone_number**

In [397]:
# Filter the rows where 'count_number_phone_1' is 8
filtered_data = processed_data[processed_data['count_number_phone_1'].isin([8])]

# Display the filtered rows
print(filtered_data[['Id_company','phone_number_1', 'count_number_phone_1']])

    Id_company phone_number_1  count_number_phone_1
83    a25dz78w       82311517                     8
237   y75ru66t       19008180                     8

In [398]:
#Because vietnamese phone number does not have the length less than 8 (except for hotline)
processed_data.loc[processed_data['phone_number_1'] == '82311517', 'phone_number_1'] = 'Not available'

**B. 9 characters in phone_number**

In [399]:
# Filter the rows where 'count_number_phone_1' is 9
filtered_data = processed_data[processed_data['count_number_phone_1'].isin([9])]

# Display the filtered rows
print(filtered_data[['Id_company','phone_number_1', 'count_number_phone_1']])

    Id_company phone_number_1  count_number_phone_1
75    l88ne80i      964728822                     9
85    r33ze56d      974128860                     9
87    u77rh51o      906191027                     9
88    h61lk13p      931876066                     9
142   y99bl33k      466585340                     9
220   w29qp17x      933715071                     9

In [400]:
# Add '0' in front of all phone numbers that are 9 digits long
processed_data.loc[processed_data['count_number_phone_1'] == 9, 'phone_number_1'] = \
    '0' + processed_data.loc[processed_data['count_number_phone_1'] == 9, 'phone_number_1']

# Update the count column after the change (now they should be 10 digits)
processed_data['count_number_phone_1'] = processed_data['phone_number_1'].str.len()

# (Optional) Re-check filtered rows
#filtered_data = processed_data[processed_data['count_number_phone_1'] == 10]
#print(filtered_data[['Id_company', 'phone_number_1', 'count_number_phone_1']].head())

<ipython-input-400-dc05b1691e7f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data['count_number_phone_1'] = processed_data['phone_number_1'].str.len()

**C. 10 characters in phone_number**

After reviewing the dataset, we observed that for one of the companies, w97bj41l, the phone number is 12 characters long. However, Vietnamese phone numbers typically have 10 or 11 digits.

This raises a question about the validity of the phone number. Specifically, because the number has 12 digits, it may not belong to Vietnam, or it could be incorrect or from another country.

In [401]:
# Filter the rows where 'count_number_phone_1' is 12
filtered_data = processed_data[processed_data['count_number_phone_1'].isin([12])]

# Display the filtered rows
print(filtered_data[['Id_company','phone_number_1', 'count_number_phone_1']])

    Id_company phone_number_1  count_number_phone_1
51    h64uj46o   002743790889                    12
123   w97bj41l   025116270419                    12

In [402]:
# Ensure 'phone_number_1' is a string type (if it's not already)
processed_data['phone_number_1'] = processed_data['phone_number_1'].astype(str)

# Specifically remove the first zero from the phone number if it starts with '0'
processed_data.loc[processed_data['Id_company'] == 'h64uj46o', 'phone_number_1'] = \
    processed_data.loc[processed_data['Id_company'] == 'h64uj46o', 'phone_number_1'].apply(lambda x: x[1:] if x.startswith('0') else x)

# Display the updated row
print(processed_data[processed_data['Id_company'] == 'h64uj46o'][['Id_company', 'phone_number_1', 'count_number_phone_1']])

   Id_company phone_number_1  count_number_phone_1
51   h64uj46o    02743790889                    12

<ipython-input-402-48e0b848c5a8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data['phone_number_1'] = processed_data['phone_number_1'].astype(str)

# Preprocess the phone_number_2

In [403]:
processed_data['count_number_phone_2'] = processed_data['phone_number_2'].str.len()
print(processed_data[['phone_number_2', 'count_number_phone_2']].head())

  phone_number_2  count_number_phone_2
0           None                   NaN
1           None                   NaN
2           None                   NaN
3           None                   NaN
4           None                   NaN

<ipython-input-403-9255cbbf1bb2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data['count_number_phone_2'] = processed_data['phone_number_2'].str.len()

In [411]:
processed_data['count_number_phone_2'].value_counts()

count_number_phone_2
10.0    37
11.0     2
0.0      1
Name: count, dtype: int64

In [405]:
processed_data['phone_number_2'] = processed_data['phone_number_2'].fillna("Not available")

<ipython-input-405-9248049bd705>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data['phone_number_2'] = processed_data['phone_number_2'].fillna("Not available")

In [406]:
# Filter the rows where 'count_number_phone_1' is 12
filtered_data = processed_data[processed_data['count_number_phone_2'].isin([0.0])]

# Display the filtered rows
print(filtered_data[['Id_company','phone_number_2', 'count_number_phone_2']])

    Id_company phone_number_2  count_number_phone_2
226   w23vc63t                                  0.0

In [407]:
processed_data.loc[processed_data['count_number_phone_2'] == 0.0, 'phone_number_2'] = 'Not available'

In [408]:
processed_data['phone_number_2'].value_counts()

phone_number_2
Not available    237
0962623839         1
0902267050         1
0834999399         1
0768165777         1
0938356533         1
0912022433         1
0812120099         1
02836360168        1
0908400188         1
0989887580         1
0905400906         1
0989885836         1
0918644259         1
0902880455         1
0343154602         1
0903602805         1
0943421949         1
0901464579         1
02838608732        1
0981206839         1
0908551658         1
0911171666         1
0981810306         1
0933260979         1
0983952019         1
0909555888         1
0911985959         1
0389978883         1
0982303035         1
0966599936         1
0902173998         1
0792434242         1
0976020699         1
0913192069         1
0975425610         1
0918083880         1
0766434535         1
0329639898         1
0968872457         1
Name: count, dtype: int64

In [409]:
processed_data

,Id_company,phone_number_1,phone_number_2,count_number_phone_1,count_number_phone_2
0,a75ky23s,02435656898,Not available,11,NaN
1,m68oe69b,0522337799,Not available,10,NaN
2,e18ju91m,0568000888,Not available,10,NaN
3,q92yc39y,1800282859,Not available,10,NaN
4,z23gg78s,0985649219,Not available,10,NaN
...,...,...,...,...,...
271,a72kv92y,0982272271,Not available,10,NaN
272,t55uj39k,0907520720,Not available,10,NaN
273,k94lu25c,0903556669,Not available,10,NaN
274,x55rh50v,0914874358,Not available,10,NaN
275,j61yg65p,0975728241,Not available,10,NaN

In [410]:
processed_data

,Id_company,phone_number_1,phone_number_2,count_number_phone_1,count_number_phone_2
0,a75ky23s,02435656898,Not available,11,NaN
1,m68oe69b,0522337799,Not available,10,NaN
2,e18ju91m,0568000888,Not available,10,NaN
3,q92yc39y,1800282859,Not available,10,NaN
4,z23gg78s,0985649219,Not available,10,NaN
...,...,...,...,...,...
271,a72kv92y,0982272271,Not available,10,NaN
272,t55uj39k,0907520720,Not available,10,NaN
273,k94lu25c,0903556669,Not available,10,NaN
274,x55rh50v,0914874358,Not available,10,NaN
275,j61yg65p,0975728241,Not available,10,NaN

# Download to Excel files

In [417]:
final_data=processed_data[['Id_company','phone_number_1','phone_number_2']]

In [421]:
import pandas as pd
from google.colab import files

# Save the processed_data to an Excel file
final_data.to_excel('/content/final_data.xlsx', index=False)

# Download the Excel file
files.download('/content/final_data.xlsx')